baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10

  [[menu.main]]
    identifier = "a-propos"
    name = "A propos"
    url = "/a-propos"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 30