baseURL = "https://www.entraide-numerique-coueron.fr/"
languageCode = "fr-fr"
title = "Entraide numérique Couëron"

[menu]
  [[menu.main]]
    identifier = "materiel"
    name = "Matériel"
    url = "/materiel"
    weight = 45
  [[menu.footer3]]
    identifier = "materiel"
    name = "Don de matériel"
    url = "/materiel"
    weight = 47