baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "a-propos"
    name = "A propos"
    url = "/a-propos"
    weight = 20