backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    path: '{{slug}}/index'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'page'
    label: 'Pages'
    folder: 'content/page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Menu', name: 'menu', widget: "select", required: false, multiple: true, options: ["main", "bottomFooter", "footer1", "footer2", "footer3" ] }
      - { label: 'Ordre dans le menu', name: 'weight', required: false, widget: "number" }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'pagelist'
    label: 'Pages List'
    folder: 'content/page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Menu', name: 'menu', widget: "select", required: false, multiple: true, options: ["main", "bottomFooter", "footer1", "footer2", "footer3" ] }
      - { label: 'Ordre dans le menu', name: 'weight', required: false, widget: "number" }
      - { label: 'Description', name: 'description', widget: 'string' }
      - label: Contenu
        name: contenu
        widget: list
        fields:
          - { label: Titre, name: heading, widget: string }
          - { label: Texte, name: text, widget: markdown }
          - { label: Image, name: imageUrl, widget: image }
  - name: "pagescustom"
    label: "Pages personnalisées"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Menu', name: 'menu', widget: "select", multiple: true, options: [ "main", "bottomFooter", "footer1", "footer2", "footer3" ] }
          - { label: 'Ordre dans le menu', name: 'weight', widget: "number" }
          - {label: "Bloc 1", name: bloc1, widget: object, fields: [
            {label: "Heading", name: "heading", widget: string},
            {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Bloc 2", name: bloc2, widget: object, fields: [
            {label: "Heading", name: "heading", widget: string},
            {label: "Text", name: "body", widget: "markdown"},
            { label: "Lien 1", name: "lien_1", widget: "string" },
            { label: "Libellé lien 1", name: "libelle_lien_1", widget: "string" },
            { label: "Lien 2", name: "lien_2", widget: "string" },
            { label: "Libellé lien 2", name: "libelle_lien_2", widget: "string" }]}
          - {label: "Bloc 3", name: "bloc3", widget: "object", fields: [
            {label: "Heading", name: "heading", widget: string},
            {label: "Text", name: "body", widget: "markdown"},
            {label: "Lien 1", name: "lien_1", widget: "string"},
            {label: "Libellé lien 1", name: "libelle_lien_1", widget: "string"},
            {label: "Lien 2", name: "lien_2", widget: "string"},
            {label: "Libellé lien 2", name: "libelle_lien_2", widget: "string"}
          ]}