backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    path: '{{slug}}/index'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'page'
    label: 'Pages'
    folder: 'content/page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Menu', name: 'menu', widget: "select", required: false, multiple: true, options: ["main", "footer" ] }
      - { label: 'Ordre dans le menu', name: 'weight', required: false, widget: "number" }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: "pagescustom"
    label: "Pages personnalisées"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Menu', name: 'menu', widget: "select", multiple: true, options: [ "main", "footer" ] }
          - { label: 'Ordre dans le menu', name: 'weight', widget: "number" }

          - {label: "Bloc 1 - Titre", name: "heading1", widget: string}
          - {label: "Bloc 1 - Text", name: "text1", widget: "markdown"}

          - { label: "Bloc 2 - Titre", name: "bloc2_heading", widget: string }
          - { label: "Bloc 2 - Text", name: "bloc2_text2", widget: "markdown" }
          - { label: "Bloc 2 - Lien 1", name: "bloc2_lien_1", widget: "string" }
          - { label: "Bloc 2 - Libellé lien 1", name: "bloc2_libelle_lien_1", widget: "string" }
          - { label: "Bloc 2 - Lien 2", name: "bloc2_lien_2", widget: "string" }
          - { label: "Bloc 2 - Libellé lien 1", name: "bloc2_libelle_lien_2", widget: "string" }

          - { label: "Bloc 3 - Titre", name: "bloc3_heading", widget: string }
          - { label: "Bloc 3 - Text", name: "bloc3_text2", widget: "markdown" }
          - { label: "Bloc 3 - Lien 1", name: "bloc3_lien_1", widget: "string" }
          - { label: "Bloc 3 - Libellé lien 1", name: "bloc3_libelle_lien_1", widget: "string" }
          - { label: "Bloc 3 - Lien 2", name: "bloc3_lien_2", widget: "string" }
          - { label: "Bloc 3 - Libellé lien 1", name: "bloc3_libelle_lien_2", widget: "string" }
